name: aasldkjbhaslkdj

on: pull_request


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: run
        run: git show && ls -l && git log -5 --graph --date=short
