name: Git status since last tag

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ruby:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: ${{github.head_ref}}
      - name: script
        run: git config --global --add safe.directory /__w/gh_actions/gh_actions && git remote -v
        
